Replaces pk_*_class with term_classification
phenoscape/rphenoscape pull request #163
Opened 2021-02-09 16:22 UTC by johnbradley

Deprecates pk_taxon_class, pk_anatomical_class, and pk_phenotype_class in favor of term_classification.
The term_classification function is renamed from the pk_class function.

2021-02-11 19:10 UTC, hlapp requested changes
See inline comment. Also, there appear to be some changes here from an earlier PR, do you maybe have to rebase? Or were these forgotten from being included earlier? If the latter, they should be their own commit and PR.

Finally, the  question is should we also renamed `@id` to `id`. The `@` prefix character is solely an artifact from JSON-LD. The change would break backwards compatibility, so here would be a good opportunity to make it. (The deprecated function would revert the name change, as older code may well depend on it.)

2021-02-11 19:10 UTC, hlapp commented on tests/testthat/test-classif.R
> +  expect_output(str(t), 'List of 5')
It seems that what you're trying to test here is (1) is the result a list; and (2) does it have 5 elements (length is 5). It seems better to me to test that explicitly (necessarily in two steps) rather than having this single step test that though relies on the output of `str()`.

Same for the next two.

2021-02-11 19:46 UTC, johnbradley commented on tests/testthat/test-classif.R
> +  expect_output(str(t), 'List of 5')
I updated the tests as suggested.

2021-02-11 19:49 UTC, johnbradley commented
> Also, there appear to be some changes here from an earlier PR, do you maybe have to rebase? Or were these forgotten from being included earlier? If the latter, they should be their own commit and PR.

@hlapp This branch is caught up with baseline-v0.3.0. What changes are you referencing?

2021-02-11 20:06 UTC, hlapp commented
> @hlapp This branch is caught up with baseline-v0.3.0. What changes are you referencing?

```
$ git show cadcc6b
commit cadcc6bea407a6fa6e76d108499f707cc96505de
Author: John Bradley <johnbradley2008@gmail.com>
Date:   Tue Feb 9 11:21:23 2021 -0500

[...]
diff --git a/man/get_studies.Rd b/man/get_studies.Rd
index c0f3e1b..1e2faac 100644
--- a/man/get_studies.Rd
+++ b/man/get_studies.Rd
@@ -4,8 +4,8 @@
 \alias{get_studies}
 \title{Query the list of studies by taxa, anatomical entities, and qualities.}
 \usage{
-get_studies(taxon = NA, entity = NA, quality = NA,
-  phenotype = NA, includeRels = c("part of"), relation = c("part of"))
+get_studies(taxon = NA, entity = NA, quality = NA, phenotype = NA,
+  includeRels = c("part of"), relation = c("part of"))
 }
 \arguments{
 \item{taxon}{character. The taxon by which to filter, if any.}
diff --git a/man/phenotype_matches.Rd b/man/phenotype_matches.Rd
index 23741f0..5d914f0 100644
--- a/man/phenotype_matches.Rd
+++ b/man/phenotype_matches.Rd
@@ -28,5 +28,5 @@ IDs). A phenotype matches if it is linked to at least one of the studies.
 x <- get_phenotypes(entity = "basihyal bone")
 nrow(x)
 # which of these are in the same study or studies as the first one?
-phenotype_matches(x, pk_get_study_list(phenotype = x$id[1]))
+phenotype_matches(x, get_studies(phenotype = x$id[1]))
 }
[...]
diff --git a/man/pkb_args_to_query.Rd b/man/pkb_args_to_query.Rd
index fcb9884..ccf9a66 100644
--- a/man/pkb_args_to_query.Rd
+++ b/man/pkb_args_to_query.Rd
@@ -8,7 +8,7 @@ pkb_args_to_query(..., includeRels = FALSE, verbose = FALSE)
 }
 \arguments{
 \item{...}{any combination of zero or more parameters from \code{entity},
-\code{quality}, \code{taxon}, and \code{study}. Any provided with value \code{NA} will be
+\code{quality}, \code{taxon}, \code{study}, and \code{phenotype}. Any provided with value \code{NA} will be
 ignored. Entity, quality, and taxon will be resolved to IRI if not
 already provided as such.}
 
diff --git a/man/profile_similarity.Rd b/man/profile_similarity.Rd
index ec2d05a..f277c66 100644
--- a/man/profile_similarity.Rd
+++ b/man/profile_similarity.Rd
@@ -87,7 +87,7 @@ the profile similarity matrix.
 \examples{
 tt <- sapply(c("pelvic fin", "pectoral fin",
                "forelimb", "hindlimb", "dorsal fin", "caudal fin"),
-             pk_get_iri, as = "anatomy")
+             get_term_iri, as = "anatomy")
 
 # define groups (profiles) as factors:
 pairedUnpaired <- c(rep("paired", times = 4), rep("unpaired", times = 2))
[...]
diff --git a/man/similarity.Rd b/man/similarity.Rd
index 4d3b9d4..baab355 100644
--- a/man/similarity.Rd
+++ b/man/similarity.Rd
@@ -37,8 +37,8 @@ information content, and where a term will always have a score equal to or
 greater than any of its superclasses. If a function, it must accept parameter
 \code{x} as the vector of term IRIs and return a vector of frequencies (\emph{not}
 IC scores) for the terms. The default is to use function \code{\link[=term_freqs]{term_freqs()}}.
-Subsumer terms with zero or missing (NA) frequency will be omitted from the
-calculation.}
+Subsumer terms with zero or missing (NA) frequency will be omitted from
+the calculation.}
 
 \item{wt_args}{list, named parameters for the function calculating term
 frequencies. Ignored if \code{wt} is not a function. For the default \code{wt}
[...]
```

2021-02-11 20:26 UTC, johnbradley commented
@hlapp These Rd files are generated by running roxygen2::roxygenise(). 
I just added all changes it generated assuming whatever it did was correct.
The first example you provided roxygen2 moved `phenotype = NA` up a line for some unknown reason.
```
-get_studies(taxon = NA, entity = NA, quality = NA,
-  phenotype = NA, includeRels = c("part of"), relation = c("part of"))
+get_studies(taxon = NA, entity = NA, quality = NA, phenotype = NA,
+  includeRels = c("part of"), relation = c("part of"))
```
Should I just delete all Rd files that do not have an equivalent R files changed on this PR?

2021-02-11 20:40 UTC, johnbradley commented
I'm going to try and resolve some of the extra Rd files by branching off base-v0.3.0 and running roxygen2::roxygenise(), then creating a PR from whatever it creates.

2021-02-11 21:31 UTC, hlapp commented
I don't think you've addressed or given your thoughts on this yet:

> Finally, the question is should we also renamed `@id` to `id`. The `@` prefix character is solely an artifact from JSON-LD. The change would break backwards compatibility, so here would be a good opportunity to make it. (The deprecated function would revert the name change, as older code may well depend on it.)

2021-02-11 21:45 UTC, johnbradley commented
I think we would need to rename `@id` recursively. The `subClassOf` and `superClassOf` also have `@id` name.
Will everywhere we call get_json_data have this problem?

2021-02-11 21:57 UTC, hlapp commented
> I think we would need to rename `@id` recursively. The `subClassOf` and `superClassOf` also have `@id` name.
> Will everywhere we call get_json_data have this problem?

Yes and yes. Renaming recursively is also what the phenotype class methods do, if you want to compare.

2021-02-11 22:27 UTC, johnbradley commented
I would like to fix `get_json_data` and be done with it, but backwards compatibility prevents that. Once the deprecated methods are eventually removed it can be streamlined. I'll look into changing `term_classification` to rename the`@id` column names tomorrow.

2021-02-15 15:47 UTC, johnbradley commented
I added a function that replaces the `@id` name with `id` for `term_classification`:
https://github.com/phenoscape/rphenoscape/blob/0d2e3365c29d8b5775533c0ce86d4f43d9f8d6b2/R/pkb_get.R#L88-L108

I had to add `@export` to the `rclean_jsonld_names` function to fix a problem with `checking examples`:
```
  > ### ** Examples
  > 
  > term_category(c("http://purl.obolibrary.org/obo/UBERON_0011618",
  +                 "http://purl.obolibrary.org/obo/PATO_0002279",
  +                 "http://purl.obolibrary.org/obo/VTO_0071642",
  +                 "http://purl.obolibrary.org/obo/MP_0030825"))
  [1] "entity"    "quality"   "taxon"     "phenotype"
  > phens <- get_phenotypes("basihyal bone")
  > term_category(phens$id[1:3])
  Error in UseMethod("rclean_jsonld_names", x) : 
    no applicable method for 'rclean_jsonld_names' applied to an object of class "character"
  Calls: term_category ... rclean_jsonld_names -> rclean_jsonld_names.list -> lapply -> FUN
  Execution halted
```
I didn't want to expose this method but this seems to be necessary for UseMethod to work in all cases.

2021-02-15 16:23 UTC, hlapp commented
> I didn't want to expose this method but this seems to be necessary for UseMethod to work in all cases.

Yes I think that's the normal pattern (i.e., to export the generic method). BTW what I didn't check is whether there's actually a JSON-LD package for R, and whether it would have an option to do the renaming. That said, it seems easy enough to do even recursively that it may not be worth adding another dependency.

2021-02-15 17:03 UTC, johnbradley commented
The only JSON-LD R library I found was [jsonld](https://docs.ropensci.org/jsonld/), but it doesn't seem to solve this naming issue.

2021-02-15 17:14 UTC, hlapp commented
> The only JSON-LD R library I found was [jsonld](https://docs.ropensci.org/jsonld/), but it doesn't seem to solve this naming issue.

Agreed.

2021-02-15 21:11 UTC, hlapp approved these changes
I'll approve here, but see inline comment. If you agree, can you add that change, and then (assuming tests still pass :-) we can merge.

2021-02-15 21:11 UTC, hlapp commented on tests/testthat/test-classif.R
>    expect_output(str(t), 'List of 5')
Looks like there are more instances of this. It looks like these are legacy code, not your change. Nonetheless, should we take the opportunity to change them all to better practices and testing explicitly for type list  and length of 5? (BTW there's a function `testthat::expect_length()`. At least there used to be.)

2021-02-15 21:57 UTC, merged