Removes pk_ prefix from term.R functions
phenoscape/rphenoscape pull request #185
Opened 2021-03-22 14:07 UTC by johnbradley

Function changes:
- Renames pk_taxon_detail() to get_taxon_detail()
- Renames pk_anatomical_detail() to get_anatomical_detail()
- Renames pk_phenotype_detail() to get_phenotype_detail()
- Renames pk_gene_detail() to get_gene_detail()
- Renames pk_is_extinct() to is_extinct()

Renames R/pk_terms.R to R/terms.R

Fixes #177

2021-03-23 00:13 UTC, hlapp requested changes
See inline comments. No matter what we end up choosing as the naming pattern, at the very least the `phenotype_detail` needs to be changed

2021-03-23 00:13 UTC, hlapp commented on R/terms.R
> +get_anatomical_detail <- function(term, verbose=FALSE) {
I think we should also correct the naming here. We're not really returning some anatomical detail, but details about an anatomy ontology term.

Choices for a better name that come to mind:
- get_anatomy_term_detail
- get_anatomy_term_info
- anatomy_term_info

My own preference is on the last one, closely followed by the second-last.

2021-03-23 00:13 UTC, hlapp commented on R/terms.R
> +get_phenotype_detail <- function(term, verbose=FALSE) {
We should make the naming here consistent with whatever we choose for anatomy terms, but also, and importantly, let's fix the misnomer. This isn't returning term info about a phenotype but about a phenotypic quality term. So spelled out in full, this would yield `phenotypic_quality_term_info()`, or `quality_term_info()` (which might sound like "high quality info" to some, though), if we go with choice# 3 for anatomy.

2021-03-23 00:13 UTC, hlapp commented on R/terms.R
> +get_gene_detail <- function(term, taxon = NA, verbose=FALSE) {
If we choose the suffix "_info" for anatomy etc, then this should be renamed accordingly too (`gene_info()`).

2021-03-23 00:13 UTC, hlapp commented on R/terms.R
> +get_term_detail <- function(term, as, verbose=FALSE) {
Perhaps it matters less because this is not exported (and thus changing its name later can't break anyone's code), but I'd suggest `get_term_info()` , at least if we're using the `_info` suffix elsewhere.

2021-03-23 00:13 UTC, hlapp commented on R/terms.R
> +get_taxon_detail <- function(term, verbose=FALSE) {
See comments for other function names. If we choose the "_info" suffix, then this will need to be changed too so as to stay consistent.

2021-03-23 12:51 UTC, johnbradley commented on R/terms.R
> +get_anatomical_detail <- function(term, verbose=FALSE) {
The `anatomy_term_info` name sounds good to me.

2021-03-23 12:57 UTC, johnbradley commented on R/terms.R
> +get_phenotype_detail <- function(term, verbose=FALSE) {
Let's go with `phenotypic_quality_term_info` to avoid potential confusion.

2021-03-23 13:00 UTC, johnbradley commented on R/terms.R
> +get_term_detail <- function(term, as, verbose=FALSE) {
Why not use `term_info()` instead of `get_term_info` for consistency with the other functions?

2021-03-23 15:19 UTC, hlapp commented on R/terms.R
> +get_term_detail <- function(term, as, verbose=FALSE) {
Yes let's do that. I was anticipating using `term_info` as a class and trying to head off name collisions (I believe function names and class names don't collide but am not 100% sure this is true in all cases). But `terminfo` (without the underscore) may well be the better class name anyway.

2021-03-24 14:07 UTC, hlapp approved these changes
As a side note, we should open a separate issue for updating outdated links to RNeXML documentation. See inline comment.

2021-03-24 14:07 UTC, hlapp commented on vignettes/rphenoscape.Rmd
>  [`nexml` object]: http://ropensci.github.io/RNeXML/reference/nexml-class.html
I just noticed that this was still using the old URL for RNeXML documentation, and actually results in a 404. The correct one is this: https://docs.ropensci.org/RNeXML/reference/nexml-class.html

Maybe this should be a separate issue and PR?

2021-03-24 14:08 UTC, merged