WIP simple terminfo class
phenoscape/rphenoscape pull request #195
Opened 2021-04-02 17:50 UTC by johnbradley

Creating this draft PR to simplify feedback.

2021-04-06 20:13 UTC, hlapp reviewed
Good start so far. See inline comments. One thing we should think about here too is how to adapt related functions we already have. For example, there is `term_classification()`. Should `terminfo()` use this instead of doing it's own invocation of `/term/classification`, or should `term_classification()` simply use `as.terminfo(., withClasssification = TRUE)$classification`, or should it be two separate implementations that don't talk directly to each other (allowing future inconsistencies to take hold).

2021-04-06 20:13 UTC, hlapp commented on R/terms.R
> +                         query = list(iri = iri),
Note that it could be considerably faster for an array of IRIs to call `/term/labels` on all of those that failed to receive a label from `/term` than to do it one by one.

Also, I'm wondering whether this shouldn't better be delegated to `get_term_label()` so as to better centralize the function of obtaining labels. However, it seems that in that case `get_term_label()` would need to get an additional option that prevents it from trying things that this function does already (such as querying classification!). Maybe `.tryHard` with default `TRUE`, which here would set to `FALSE`.

Thoughts?

2021-04-06 20:13 UTC, hlapp commented on R/terms.R
> +        paste(x$synonyms$value, collapse = "\n    ", sep = ""),
I'm wondering whether we can add the type of synonym here too?

2021-04-07 14:51 UTC, johnbradley commented on R/terms.R
> +  res <- lapply(x, function(elem) {
To fix this I added a method to handle this case: 
https://github.com/phenoscape/rphenoscape/blob/b149b0224e81a483d93077a43601172c70e36e04/R/terms.R#L203-L206
My thought is you might have a terminfo without classsification that you want to add classification info into.

2021-04-07 16:09 UTC, hlapp commented on R/terms.R
> +        paste(x$synonyms$value, collapse = "\n    ", sep = ""),
As per Zoom meeting, can we massage these to make human-readable: (i) remove everything before and including the `oboInOwl#`; (ii) bonus points for converting the remaining "hasExactSynonym" into "(exact)" (I think a regex should be able to catch the part between "has" and "Synonym"?):

```
...
Synonyms:
    basihyoid (exact)
    glossohyal (exact)
    foo (broad)
...
```

2021-04-07 16:20 UTC, balhoff commented on R/terms.R
> +        paste(x$synonyms$value, collapse = "\n    ", sep = ""),
I just use a more brute force approach in the web UI: https://github.com/phenoscape/phenoscape-kb-web-ui/blob/bf325c5bdaf47173e5f023f135586550933bb3ad/src/main/scala/org/phenoscape/kb/ui/Vocab.scala#L34-L38 :-)

2021-04-07 19:31 UTC, hlapp commented on R/terms.R
> +        paste(x$synonyms$value, collapse = "\n    ", sep = ""),
Great! Can you surround them parentheses so it's clear the synonym type is not an extension of the synonym? Or did I miss where you do this already?

2021-04-07 20:03 UTC, johnbradley commented on R/terms.R
> +                         query = list(iri = iri),
I moved the null label fixing logic to the `as.terminfo.default` function to improve performance. This will fetch all the backup term labels in one request using `get_term_label()`. Instead of adding `.tryHard` I added a boolean `.tryClassification`.
Here is the current null label fixing logic:

https://github.com/phenoscape/rphenoscape/blob/9372b2fcf586167d210b72c083867a50f7f2821b/R/terms.R#L190-L204

The logic seems kind of verbose. There may be a simple approach to list manipulation that I am unaware of.

2021-04-07 20:06 UTC, johnbradley commented on R/terms.R
> +        paste(x$synonyms$value, collapse = "\n    ", sep = ""),
I added a change for the parentheses. This is how it looks now:
```
> as.terminfo('http://purl.obolibrary.org/obo/UBERON_0011618')
terminfo 'basihyal bone' http://purl.obolibrary.org/obo/UBERON_0011618
Definition: Replacement bone that is median and is the anterior-most bone of the ventral hyoid arch.
Synonyms:
    basihyoid (exact)
    glossohyal (exact)
...
```

2021-04-07 21:25 UTC, hlapp commented on R/terms.R
> +                         query = list(iri = iri),
I think this looks fine. You could also assemble a data.frame with ID and label, which is easy to subset for invoking `get_term_label()`, and for assigning the results. You could then try `mapply()` to stitch them back into the list of terminfos. But I doubt any of that would be significantly faster or more readable than what you have. So I think it's fine what you have.

2021-04-07 21:26 UTC, hlapp commented on R/terms.R
> +get_term_label <- function(term_iris, preserveOrder = FALSE, verbose = FALSE, .tryClassification = TRUE) {
I think you'll need to include this in the function documentation, though. Otherwise R CMD check is going to complain about an undocumented parameter.

2021-04-07 21:31 UTC, hlapp commented
Note BTW that the following now needs to be pulled out of surrounding `if` clause:
https://github.com/phenoscape/rphenoscape/pull/195/files#diff-e263dea1a5171f9e454ce0db926498542a6ada744edecbf5a5e69bcfaa7e46c5R165-R168

This needs to executed if `nrow(.) > 0` regardless of the value of `.tryClassification`.

2021-04-08 14:22 UTC, johnbradley commented on R/terms.R
> +get_term_label <- function(term_iris, preserveOrder = FALSE, verbose = FALSE, .tryClassification = TRUE) {
I added a comment for this parameter. I intend to go back and document the new functionality at the end.

2021-04-16 21:45 UTC, hlapp requested changes
Looks great, just two small change requests.

2021-04-16 21:45 UTC, hlapp commented on R/terms.R
> +#' term_iri <- find_term('Coralliozetus angelicus')
The more typical case will be an anatomy or other ontology term, so this should also include an example for one of those, especially since the output (printed properties) will slightly differ.

2021-04-16 21:45 UTC, hlapp commented on tests/testthat/test-pk.R
> +  objs <- as.terminfo(terms$id)
Include a test that `terms$id` really is a vector with length > 1. (We know KB content can change, so we want to make sure that when we say we test vectorized that we indeed do.)

2021-04-19 12:34 UTC, johnbradley commented on R/terms.R
> +#' term_iri <- find_term('Coralliozetus angelicus')
I updated the examples adding an example for `basihyal bone`:

https://github.com/phenoscape/rphenoscape/blob/279f30658b0cf7089ac3e831e2532d2dd7a962a2/R/terms.R#L202-L214

2021-04-19 12:35 UTC, johnbradley commented on tests/testthat/test-pk.R
> +  objs <- as.terminfo(terms$id)
I added a check that the length is > 1 for terms:
https://github.com/phenoscape/rphenoscape/blob/279f30658b0cf7089ac3e831e2532d2dd7a962a2/tests/testthat/test-pk.R#L313-L315

2021-04-19 14:33 UTC, hlapp commented on tests/testthat/test-pk.R
> +  objs <- as.terminfo(terms$id)
Maybe you'll hate R now, but if applied to a a data.frame, `length()` returns the number of columns, not the number of rows. For the latter you have to use `now()`.

```R
> length(data.frame(a=c(1,2)))
[1] 1
> nrow(data.frame(a=c(1,2)))
[1] 2
```

2021-04-19 14:38 UTC, hlapp requested changes
See inline suggestion and comment. Wouldn't it be useful to include an example that sets `withClassification = TRUE`?

2021-04-19 14:38 UTC, hlapp commented on R/terms.R
> +#' # find another term iri
```suggestion
#' # taxon terms have additional properties: 
```

Nitpicking here, but I think it's useful as this isn't just some other term IRI.

2021-04-19 14:58 UTC, johnbradley commented on tests/testthat/test-pk.R
> +  objs <- as.terminfo(terms$id)
I updated the code to check the length of `terms$id` since that's what I am passing into `as.terminfo()`:
https://github.com/phenoscape/rphenoscape/blob/b89781c319f48a83a9d27f80c75deee1b42c0c26/tests/testthat/test-pk.R#L313-L315
I did remember there was something odd about `length()`, but I accidentally tested a 4x4 data.frame. 😄

2021-04-19 15:21 UTC, johnbradley commented
I added a withClassification example to the as.terminfo examples:
https://github.com/phenoscape/rphenoscape/blob/a16c493b7d2e81c6e266bb97c568103fae05d13c/R/terms.R#L201-L222

2021-04-21 15:00 UTC, hlapp approved these changes
My remaining two suggestions / comments are minor, so I'll approve this here in advance. Please consider before merging.

2021-04-21 15:12 UTC, johnbradley commented on R/terms.R
> +#' term_iri <- find_term('basihyal bone', matchType='exact')
I thought a user might copy the `classification details can be requested:` block from the examples and paste it into the R console and get an error. If you think that is unlikely I can remove the `term_iri <- find_term(...` line.

2021-04-21 16:07 UTC, hlapp commented on R/terms.R
> +#' term_iri <- find_term('basihyal bone', matchType='exact')
I don't think of the `@examples` section as a series of examples each of which stands on its own and can be copied on its own. But you could keep that ability _and_ avoid full redundancy by using a different term, say "maxilla". Or "pectoral fin".

2021-04-21 17:26 UTC, merged