Adds Owl class for use with get_ontotrace_data()
phenoscape/rphenoscape pull request #197
Opened 2021-05-04 18:11 UTC by johnbradley

Updates get_ontotrace_data() to support passing Manchester OWL
expressions via the Owl class for the taxon and entity parameters.

Adds as.owl() and resolve_label_expression() functions that
return an Owl object that can be passed as taxon and entity to
get_ontotrace_data().

The as.owl() function receives a character vector containing
Manchester OWL expressions and adds the "owl" class if necessary.

The resolve_label_expression() function receives a character
containing a Manchester OWL expression containing labels instead
of IRI.  The /term/resolve_label_expression API endpoint is used
to resolve the label-based class expression into an valid
Manchester OWL expression and adds the "owl" class.

Adds subsume parameter to the get_ontotrace_data() to turn off
subsumption when passing in a vector of labels or IRI to
taxon/entity. This parameter defaults to TRUE and does not
work when passing owl data.

---

# Draft Feedback
Creating this draft PR to get feedback on the initial function changes.
Tests and documentation still need to be written/updated.

2021-05-04 18:11 UTC, johnbradley commented
## Examples

### Label-based OWL Manchester class expressions
Recreating the example from  `https://kb.phenoscape.org/#/ontotrace` that creates NeXML for a label-based OWL Manchester class expressions.
```
> taxon <- resolve_label_expression("Characiformes or Siluriformes")
> entity <- resolve_label_expression("'skeletal element' and ('part of' some fin)")
> get_ontotrace_data(taxon, entity)
A nexml object representing:
...
  Taxa:	 Breitensteinia insignis, Malapterurus beninensis, Horiomyzon retropinnatus, Odontostoechus lethostigmus, Oligosarcus longirostris, Trachycorystes trachycorystes ...
...
Generated from the Phenoscape Knowledgebase on 2021-5-3 by Ontotrace query :
* taxa: <http://purl.obolibrary.org/obo/VTO_0034991> or <http://purl.obolibrary.org/obo/VTO_0037519>
* taxa list: Not provided 
* entities: <http://purl.obolibrary.org/obo/UBERON_0004765> and (<http://purl.obolibrary.org/obo/BFO_0000050> some <http://purl.obolibrary.org/obo/UBERON_0008897>)
* entity list: Not provided 
* variable only: true
...
```

### OWL Manchester class expressions
Same as previous example but with explicit OWL class expressions.
```
> taxon <- as.owl("<http://purl.obolibrary.org/obo/VTO_0034991> or <http://purl.obolibrary.org/obo/VTO_0037519>")
> entity <- as.owl("<http://purl.obolibrary.org/obo/UBERON_0004765> and (<http://purl.obolibrary.org/obo/BFO_0000050> some <http://purl.obolibrary.org/obo/UBERON_0008897>)")
> get_ontotrace_data(taxon, entity)
```

### Turn off subsumption for a list of taxon/entity IRI
IRI taken from the rphenoscape ontotrace example 
Example taken from http://rphenoscape.phenoscape.org/articles/rphenoscape.html#character-matrix-via-ontotrace

```
> get_ontotrace_data(taxon="http://purl.obolibrary.org/obo/VTO_0061498",
                   entity="http://purl.obolibrary.org/obo/UBERON_2002002",
                   variable_only = FALSE,
                   subsume = FALSE)
A nexml object representing:
...
Generated from the Phenoscape Knowledgebase on 2021-5-4 by Ontotrace query :
* taxa: Not provided
* taxa list: [http://purl.obolibrary.org/obo/VTO_0061498] 
* entities: Not provided
* entity list: [http://purl.obolibrary.org/obo/UBERON_2002002] 
* variable only: false
```

The above would also work for names instead of IRIs.

2021-06-04 12:34 UTC, johnbradley commented
The github action tests are failing due to timeouts fetching data from kb.phenoscape.org/api.
For example `corpus_size("taxa")` is failing.
I don't think these problems are related to changes here.

2021-06-07 20:04 UTC, hlapp requested changes
Nice work! See various inline comments and edits. Note that OWL is an acronym and should thus be given in upper case. Also, the canonical reference to the format is "OWL Manchester syntax", not "Manchester OWL", and I'm thus wondering whether the class name shouldn't better be `owlmn` instead of `mnowl`.

2021-06-07 20:04 UTC, hlapp commented on R/owl_obj.R
> +  owlformatclass = "mnowl"
Shouldn't this best be a file-wide (i.e., package environment) setting, like a constant (possibly using ALL CAPS). You are referring to this in multiple places in the code.

2021-06-07 20:07 UTC, hlapp commented
> The github action tests are failing due to timeouts fetching data from kb.phenoscape.org/api.
> I don't think these problems are related to changes here.

I agree they don't seem related to changes here. But the failures also appear reproducible, and only so for the release version. This suggests that a more current release of the cURL library or rCurl introduce this 10s timeout (or do not automatically extend it anymore?), and that we may need to explicitly request a longer timeout.

2021-06-07 20:58 UTC, johnbradley commented on R/owl_obj.R
> +#' as.owl("'fin spine' and ('part of' some 'fin spine')")
This was an example that I thought I had removed. An earlier version of `as.owl` tried to automatically handle labels, but I never figured out a satisfactory way to do that. Adding the __usesLabels__ parameter seems like a good option. 
I really like defaulting __usesLabels__ to TRUE. From my perspective the labeled version is easier to understand first.

2021-06-08 12:43 UTC, johnbradley commented on R/owl_obj.R
> +#' as.owl("'fin spine' and ('part of' some 'fin spine')")
After further thought I think we should default __usesLabels__ to FALSE. Since OWL Manchester Syntax is a W3C standard and the label-based notation is not.

2021-06-08 15:18 UTC, johnbradley commented on R/owl_obj.R
> +#'   The character vector must be a valid  OWL expression appropriate for the format.
I added a link in the `usesLabels` parameter documentation.

2021-06-08 15:19 UTC, johnbradley commented on tests/testthat/test-ontotrace.R
> +  testthat::expect_gte(length(nex1@otus[[1]]@otu), 2)
Correct. I updated the test.

2021-06-08 15:25 UTC, hlapp commented on R/owl_obj.R
> +#' as.owl("'fin spine' and ('part of' some 'fin spine')")
Good point, I agree!

2021-06-08 15:40 UTC, johnbradley commented on tests/testthat/test-ontotrace.R
> +  testthat::expect_gte(length(nex1@otus[[1]]@otu), 2)
For the `at most one character` part I added this check:
https://github.com/phenoscape/rphenoscape/blob/34c218df6aa4faacf2dc1659dcdfb6f0673544e0/tests/testthat/test-ontotrace.R#L101

2021-06-08 15:44 UTC, hlapp commented on tests/testthat/test-ontotrace.R
> +  testthat::expect_gte(length(nex1@otus[[1]]@otu), 2)
This tests that there is at most one characters block, not one character. I think you'll want to use the same subsetting as for OTUs (i.e., select the first characters block, then see how many characters (`\@char` I believe) there are in this block.

2021-06-08 15:55 UTC, johnbradley commented on tests/testthat/test-ontotrace.R
> +  testthat::expect_gte(length(nex1@otus[[1]]@otu), 2)
There is a `@char` underneath `@format` within the characters block :`nex1@characters[[1]]@format@char`.
That list contains one item with a label "anterior dentation of pectoral fin spine".
Is this the correct field to check?

2021-06-08 15:57 UTC, hlapp commented on tests/testthat/test-ontotrace.R
> +  testthat::expect_gte(length(nex1@otus[[1]]@otu), 2)
Ah yes, I forgot the `@format`. Indeed, this would be the list of characters.

2021-06-09 22:26 UTC, hlapp requested changes
A few small changes and some suggestions. Almost there.

2021-06-09 22:26 UTC, hlapp commented on R/owl_obj.R
> +#' @param format type of owl syntax passed in owlstr - currently only "manchester" is allowed
```suggestion
#' @param format the OWL syntax to which `owlstr` conforms - currently only "manchester" (for [OWL Manchester Syntax](https://www.w3.org/2007/OWL/draft/owl2-manchester-syntax/)) is allowed
```

2021-06-09 22:26 UTC, hlapp commented on R/owl_obj.R
> +#'   or a list of such objects.
```suggestion
#'   or a list of such objects. Note that (at least currently) these are in essence character strings, and are recognizable as such by R.
```

2021-06-09 22:26 UTC, hlapp commented on R/owl_obj.R
> +#' as.owl("'fin spine' and ('part of' some 'fin spine')", usesLabels = TRUE)
Can we add a `is.character()` test here demonstrating that these objects remain valid R character strings? (Arguably this should probably also be added to the tests?)

2021-06-09 22:26 UTC, hlapp commented on R/owl_obj.R
> +#' @return A object of class "owl" with a resolved OWL Manchester expression composed of IRIs
Can we add here as well that objects are still valid R character strings as per suggested change to `as.owl()` documentation?

2021-06-09 22:26 UTC, hlapp commented on R/owl_obj.R
> +#' @return A object of class "owl" with a resolved OWL Manchester expression composed of IRIs
And BTW, as a function that's part of the package's exported API, it doesn't add anything anymore over `as.owl(., usesLabels = TRUE)`, does it? Meaning it would be redundant? If yes, shouldn't we no longer export it? (Every function that's exported will need to be maintained somehow in the future, so less is more in this regard.)

2021-06-09 22:26 UTC, hlapp commented on R/pk_ontotrace.R
> +#'   or a single OWL Manchester expression object.
Add a link here to `as.owl()`?

2021-06-09 22:26 UTC, hlapp commented on R/pk_ontotrace.R
> +#'   or a single OWL Manchester expression object.
Add a link here to `as.owl()`?

2021-06-09 22:26 UTC, hlapp commented on tests/testthat/test-owl.R
> +  testthat::expect_true(is.manchester_owl(obj))
Add test here that it's still a character string?

2021-06-09 22:26 UTC, hlapp commented on tests/testthat/test-owl.R
> +  testthat::expect_true(is.manchester_owl(result))
Add test here that it's still a character string?

2021-06-10 15:06 UTC, johnbradley commented on R/owl_obj.R
> +#' @return A object of class "owl" with a resolved OWL Manchester expression composed of IRIs
I removed export from `resolve_label_expression()`.

2021-06-10 15:12 UTC, johnbradley commented on tests/testthat/test-owl.R
> +  testthat::expect_true(is.manchester_owl(obj))
Done.

2021-06-10 15:12 UTC, johnbradley commented on tests/testthat/test-owl.R
> +  testthat::expect_true(is.manchester_owl(result))
Done.

2021-06-10 15:12 UTC, johnbradley commented on R/owl_obj.R
> +#' as.owl("'fin spine' and ('part of' some 'fin spine')", usesLabels = TRUE)
Done.

2021-06-10 15:12 UTC, johnbradley commented on R/pk_ontotrace.R
> +#'   or a single OWL Manchester expression object.
Done.

2021-06-10 15:12 UTC, johnbradley commented on R/pk_ontotrace.R
> +#'   or a single OWL Manchester expression object.
Done.

2021-06-10 19:59 UTC, hlapp approved these changes
See minor example and test edits to be consistent with each other and the public package API.

As a teensy nitpick, is there a reason you're using `expect_true(is.foo(.))` for some and `expect_is(obj, "foo")` for other tests?  

Forgot to add, I'm approving this because the remaining comments are all relatively trivial and I don't need to review this again after whatever you decide to do in response to the edits and above comments.

2021-06-10 19:59 UTC, hlapp commented on R/pk_ontotrace.R
> +#' taxon_owl <- resolve_label_expression("Ictalurus")
```suggestion
#' taxon_owl <- as.owl("Ictalurus", usesLabels = TRUE)
```

2021-06-10 19:59 UTC, hlapp commented on R/pk_ontotrace.R
> +#' entity_owl <- resolve_label_expression("'fin' or ('part of' some 'fin')")
```suggestion
#' entity_owl <- as.owl("'fin' or ('part of' some 'fin')", usesLabels = TRUE)
```

2021-06-10 19:59 UTC, hlapp commented on man/get_ontotrace_data.Rd
> +taxon_owl <- resolve_label_expression("Ictalurus")
```suggestion
taxon_owl <- as.owl("Ictalurus", usesLabels = TRUE)
```

2021-06-10 19:59 UTC, hlapp commented on man/get_ontotrace_data.Rd
> +entity_owl <- resolve_label_expression("'fin' or ('part of' some 'fin')")
```suggestion
entity_owl <- as.owl("'fin' or ('part of' some 'fin')", usesLabels = TRUE)
```

2021-06-10 19:59 UTC, hlapp commented on tests/testthat/test-ontotrace.R
> +  taxon <- resolve_label_expression("Ictalurus")
```suggestion
  taxon <- as.owl("Ictalurus", usesLabels = TRUE)
```

2021-06-10 19:59 UTC, hlapp commented on tests/testthat/test-ontotrace.R
> +  entity <- resolve_label_expression("'paired fin bud' or ('develops from' some 'paired fin bud')")
```suggestion
  entity <- as.owl("'paired fin bud' or ('develops from' some 'paired fin bud')", usesLabels = TRUE)
```

2021-06-11 11:55 UTC, johnbradley commented
> As a teensy nitpick, is there a reason you're using expect_true(is.foo(.)) for some and expect_is(obj, "foo") for other tests?

This was intentional to test that is.foo is checking the correct class.
For example the following test checks `obj` is "owl" and the `is.owl` function returns true:
https://github.com/phenoscape/rphenoscape/blob/f6e7ae14e77f0f907125e7e3681b71777421f1cd/tests/testthat/test-owl.R#L11-L12

2021-06-11 15:58 UTC, merged