Removes IRI interpretation from term_category()
phenoscape/rphenoscape pull request #216
Opened 2021-06-23 14:08 UTC by johnbradley

Changes term_category to return NA when category cannot be
determined with high confidence. Removes IRI decoding since
IRIs should be opaque.

Fixes #215

2021-06-24 13:58 UTC, johnbradley commented on tests/testthat/test-freqs.R
> +  testthat::expect_identical(wt1, wt)
This check was moved to this section of this test because no categories were found for the IRIs returned by `get_phenotypes(entity = "pelvic fin", quality = "shape")` below.

2021-06-29 21:56 UTC, hlapp reviewed
See notes. Maybe needs a little more discussion.

2021-06-29 21:56 UTC, hlapp commented on tests/testthat/test-freqs.R
> +  type.fracs <- table(tt.types)/length(tt.types)
I'm wondering whether we shouldn't rethink the objective of this test. With this change, what we're testing is whether for those terms for which a category _could_ be determined, whether the vast majority (>90%) of them fall into the same (and thus assumed as correct) category. If we don't care (because we don't test) how many we're removing as category indeterminable, then that's somewhat meaningless. (For example, if we end up removing 90% of the terms as indeterminable, what does it mean if 90% of the remaining 10% (i.e., 9% of the total) end up in the same category.)

It would seem to make more sense to have some kind of minimum expectation for the fraction of terms for which we can determine category, and that among those for which we can, the result is incorrect for at most very few.

2021-06-29 21:56 UTC, hlapp commented on tests/testthat/test-freqs.R
> +  testthat::expect_identical(wt1, wt)
Perhaps this should be left as a failing test then. Essentially it would mean that phenotype as category is rarely possible to determine if it's the correct one. This didn't use to be so; if it is the case now, it deserves attention. Either in the form of fixing this in the database, or alternatively it makes me wonder whether eliminating phenotype as one of the possible returned categories isn't the right answer. (The phenotype ontologies that would make determining "phenotype" as category deterministically possible, such as MP or HPO, are not used for the evolutionary phenotypes. They _are_ used for corresponding gene phenotypes, though (namely mouse and human, respectively).)

2021-06-30 13:50 UTC, johnbradley commented on tests/testthat/test-freqs.R
> +  type.fracs <- table(tt.types)/length(tt.types)
Currently 12% of the term categories are indeterminable (category is NA).
I added a check that no more than 15% are NA.

2021-06-30 14:15 UTC, johnbradley commented on tests/testthat/test-freqs.R
> +  testthat::expect_identical(wt1, wt)
With the current code I don't think `term_category()` will ever return "phenotype" category.
(One exception is if they object passed in is of type "phenotype"). Previously the assumption was if you can't figure it out it must be "phenotype".

2021-07-01 13:57 UTC, johnbradley commented
Holding off on this PR in favor of waiting for a kb.phenoscape API change to help determine category for an IRI.

2021-07-01 17:39 UTC, johnbradley commented
Re-opening  and switching to Draft to remove the IRI decoding reliant features.
Once the kb.phenoscape API category changes are ready another PR may be created to add back in removed features.

2021-07-13 14:01 UTC, johnbradley commented
Something I missed in [term_category()](https://github.com/phenoscape/rphenoscape/blob/6b59eda736431a8f25e08969eebe2dcbbf3c3150/R/term-type.R#L25-L29) is how [obo_prefix()](https://github.com/phenoscape/rphenoscape/blob/6b59eda736431a8f25e08969eebe2dcbbf3c3150/R/term-type.R#L117-L130) and [obo_ont_type()](https://github.com/phenoscape/rphenoscape/blob/6b59eda736431a8f25e08969eebe2dcbbf3c3150/R/term-type.R#L82-L99) can determine an IRI category is "phenotype":
https://github.com/phenoscape/rphenoscape/blob/6b59eda736431a8f25e08969eebe2dcbbf3c3150/R/term-type.R#L27-L29

`obo_prefix()` relies upon the IRI matching `purl.obolibrary.org`:
https://github.com/phenoscape/rphenoscape/blob/6b59eda736431a8f25e08969eebe2dcbbf3c3150/R/term-type.R#L127-L128

`obo_ont_type()` can then determine the category as "phenotype" based on the prefix:
https://github.com/phenoscape/rphenoscape/blob/6b59eda736431a8f25e08969eebe2dcbbf3c3150/R/term-type.R#L92-L97

2021-07-13 14:38 UTC, hlapp requested changes
See inline comments. In essence, I think stronger provisions for backwards compatibility (or raising an error where this isn't possible because some parameter value is no longer supported) are needed.

2021-07-13 14:38 UTC, hlapp commented on R/term-weights.R
> -                       decodeIRI = TRUE,
So this would remove backwards compatibility immediately (as compared to going through a round of deprecation) for anyone who specified this parameter. Those who did most likely set it to `FALSE` (because `TRUE` is/was the default), which would actually be fine. So I'm wondering whether we shouldn't leave the parameter for now, default it to `FALSE` instead of `TRUE`, and give a deprecation warning (about the parameter being deprecated) when the parameter is not missing but set to `FALSE`, and `stop()`ing if it is set to `TRUE` (because this is now no longer supported).

2021-07-13 14:38 UTC, hlapp commented on R/term-weights.R
> -
I may be missing something but it seems with this and the preceding deletion we are not checking whether someone passes `"auto"` as the value, as was previously allowed. We'd need to catch this and raise `stop()` rather than silently ignoring it.

2021-07-13 15:09 UTC, johnbradley commented on R/term-weights.R
> -                       decodeIRI = TRUE,
Having a boolean value that can only be FALSE is kinda weird to me, but I get that if a user was already passing `decodeIRI = FALSE` that would be fine. Wouldn't changing the default value of `decodeIRI` from `TRUE` to `FALSE` remove backwards compatibility? If you want to keep backwards compatibility from the rphenoscape-code perspective I think we would need to remove this logic on a later release and just show a deprecation warning in the 0.3.0 release. When you take into account changes in IRI's returned by the new kb.phenoscape.org API we have a breaking change on 0.3.0 no matter what.

I'll try out the boolean that must be FALSE version so we can see how that looks.

2021-07-13 15:16 UTC, johnbradley commented on R/term-weights.R
> -
The match.arg function raises an error if you pass in a bogus parameter value for `as`:
```
> phens <- get_phenotypes(entity = "basihyal bone")
> term_freqs(phens$id, as = "auto", corpus = "taxa")
 Error in match.arg(as, several.ok = TRUE) : 
  'arg' should be one of “entity”, “quality”, “phenotype” 
```
The `as` parameter is now defaulted to 
`as = c("entity", "quality", "phenotype"),`
And the `match.arg` function is called like so:
`as <- match.arg(as, several.ok = TRUE)`.
I will admit I found match.arg surprising since it's reading both the default value and the passed in parameter value.

2021-07-13 15:25 UTC, hlapp commented on R/term-weights.R
> -
I see. 👍🏻

2021-07-13 15:55 UTC, johnbradley commented on R/term-weights.R
> -                       decodeIRI = TRUE,
I pushed a couple commits adding the FALSE-only decodeIRI param back. Having some documentation about how that parameter has changed does seem like an improvement.

2021-07-13 18:22 UTC, hlapp approved these changes
I think it looks good now. See me inline edits and I also added a larger edit for documentation where it was still talking about auto-determining category.

2021-07-13 18:22 UTC, hlapp commented on R/term-weights.R
> +#' category was an option, but this is no longer supoported, in part because it
```suggestion
#' category was an option, but this is no longer supported, in part because it
```

2021-07-13 19:00 UTC, merged