Removes term_freqs taxon_annotations corpus
phenoscape/rphenoscape pull request #226
Opened 2021-07-16 15:26 UTC by johnbradley

Removes the ability to use `corpus = "taxon_annotations"` with `term_freqs()`.
This means the only `corpus` supported are "taxa" and "genes".
The `as` parameter is also restricted to "phenotype" now, because this is the only value supported by "taxa" and "genes".

Fixes #214

TODO: Finish updating term_freqs() documentaiton.

2021-07-22 15:47 UTC, hlapp requested changes
See inline comments. As for `tests/testthat/test-semsim.R`, there's not much point in changing the corpus from taxon_annotations to taxa. It just makes the tests redundant (the full dataset is already tested for corpus taxa, testing a subsample is redundant). And the subsampling is so that the tests execute in reasonable time because taxon_annotations used to be very slow. Hopefully, once supported by the API directly, the subsampling for execution time reasons won't be necessary anymore.

2021-07-22 15:47 UTC, hlapp commented on R/term-weights.R
> +#' only supported value for the as parameter is "phenotype" since "entity" and
```suggestion
#' only supported value for the `as` parameter is "phenotype" since "entity" and
```

2021-07-22 15:47 UTC, hlapp commented on R/term-weights.R
> +#'   support for "entity" and "quality" have been deprecated as of v0.3.x)
```suggestion
#'   support for "entity" and "quality" has been disabled as of v0.3.0, pending full support from the KB API.)
```

2021-07-22 15:47 UTC, hlapp commented on R/term-weights.R
> +#'   categories (of same length as `x`). The default is phenotype".
```suggestion
#'   categories (of same length as `x`). The default is "phenotype".
```

2021-07-22 15:47 UTC, hlapp commented on R/term-weights.R
>  #'   "genes". (At present, support for "gene_annotations" is pending support in
```suggestion
#'   "genes". (At present, support for "gene_annotations" and "taxon_annotations" is disabled, pending support in
```

2021-07-22 15:47 UTC, hlapp commented on R/term-weights.R
> +#'   the Phenoscape API. The "taxon_annotations" corpus support has been deprecated
```suggestion
#'   the Phenoscape KB API.)
```

2021-07-22 15:47 UTC, hlapp commented on R/term-weights.R
> +#'   as of v0.3.x) The default is "taxa".
```suggestion
#'   The default is "taxa".
```

2021-07-22 15:47 UTC, hlapp commented on R/term-weights.R
> +#' term_freqs(IRIs, as = "phenotype")
This won't work because the terms aren't phenotypes. I.e., we shouldn't "fix" code snippets like this mis-representing their category.

2021-07-22 15:47 UTC, hlapp commented on tests/testthat/test-freqs.R
> +  wt <- term_freqs(tt, as = "phenotype")
Again, this won't work if we pretend the terms to be something that they're not.

2021-07-22 15:47 UTC, hlapp commented on tests/testthat/test-freqs.R
> +  wt1 <- term_freqs(tt, as = "phenotype", corpus = "taxa")
See above.

2021-07-22 15:47 UTC, hlapp commented on tests/testthat/test-freqs.R
> +  testthat::expect_error(term_freqs(phens$id, as = "entity", corpus = "taxa"))
Isn't this the same line repeated twice?

2021-07-22 17:53 UTC, johnbradley commented on R/term-weights.R
> +#' term_freqs(IRIs, as = "phenotype")
The category of various terms is still a little fuzzy for me. 
Would "pectoral fin present" be a phenotype term that a user would want to calculate frequency of?
I'm not sure what a good example of running term_freqs() with a phenotype term would look like.
Perhaps something like this:
```
phens <- get_phenotypes(entity = "pectoral fin", quality = "present")
term_freqs(phens$id, as="phenotype")
```

2021-07-22 18:37 UTC, hlapp commented on R/term-weights.R
> +#' term_freqs(IRIs, as = "phenotype")
Yes. All terms returned by `get_phenotypes()` are of category phenotype. Entities are, for example, anatomical elements.  A phenotype is (in our logic model) a quality that inheres in an entity. So technically (or I should say logically), at the least in the original EQ model, phenotypes are subclasses of qualities.

2021-07-23 13:27 UTC, johnbradley commented on R/term-weights.R
> +#' term_freqs(IRIs, as = "phenotype")
I removed this example since we already had a "phenotype" example below it.

2021-07-23 13:30 UTC, johnbradley commented on tests/testthat/test-freqs.R
> +  wt <- term_freqs(tt, as = "phenotype")
I replaced this test with a simpler one that just tests phenotype term frequencies.

2021-07-23 13:31 UTC, johnbradley commented
For `tests/testthat/test-semsim.R` I removed the "taxon_annotations" portion of the failing test.

2021-07-23 16:06 UTC, hlapp approved these changes
See inline comments. These are minor, so I'm leaving their consideration to you.

2021-07-23 16:06 UTC, hlapp commented on R/term-weights.R
> -#' term_freqs(phens$id, as = "phenotype", corpus = "taxa")
Why not keep the "taxa" corpus example? It's the more relevant anyway.

2021-07-23 16:06 UTC, hlapp commented on tests/testthat/test-freqs.R
>    wt1 <- term_freqs(phens$id, as = "phenotype", corpus = "taxa")
So this tests whether `wt` used "taxa" as then default corpus, right? Maybe add that as a comment so it's clearer what's being tested for?

2021-07-23 17:35 UTC, merged