Combines NeXML char matrix functions
phenoscape/rphenoscape pull request #228
Opened 2021-08-11 14:23 UTC by johnbradley

Replaces pk_get_ontotrace() and pk_get_study() with get_char_matrix().
get_char_matrix() has arguments to allow users to return symbols or
labels for states. This removed the need for two functions. Users should
now use lapply to transform lists of NeXML using get_char_matrix().

Replaces pk_get_ontotrace_meta() and pk_get_study_meta() with
get_char_matrix_meta(). The only difference between the two
pk_get_*_meta functions was the study version did not fetch
entity metadata. get_char_matrix_meta() always fetches
entity metadata.

Fixes #172

2021-08-11 14:38 UTC, johnbradley commented
Outside of `pk_get_study_meta()` processing a list of NeXML. The main difference between `pk_get_study_meta()` and `pk_get_ontotrace_meta()` is the following code:


https://github.com/phenoscape/rphenoscape/blob/b367c4416af4cc6fa45a00765ce45a8d412b5c22/R/pk_ontotrace.R#L49-L54

https://github.com/phenoscape/rphenoscape/blob/b367c4416af4cc6fa45a00765ce45a8d412b5c22/R/pk_study.R#L224-L226

I don't know why the call to `get_metadata` was commented out, but in my testing it worked fine for study NeXML data. Git blame found [this commit](https://github.com/phenoscape/rphenoscape/commit/5fef0d86e45967cd446e39bca3c76a3a2eb4433e). Looks like the original code was committed with get_metadata commented out.

2021-08-11 15:55 UTC, hlapp requested changes
See inline comments.

2021-08-11 15:55 UTC, hlapp commented on R/nexml.R
> +#' Returns a NeXML-format evolutionary character matrix.
```suggestion
#' Obtains a character-state matrix from a nexml object
```

2021-08-11 15:55 UTC, hlapp commented on R/nexml.R
> +#' @param nex, a nexml object
```suggestion
#' @param nex, a [nexml][[RNeXML::nexml-class] object
```

2021-08-11 15:55 UTC, hlapp commented on R/nexml.R
> +#' @return data.frame: The character matrix.
```suggestion
#' @return data.frame: The character-state matrix.
```

2021-08-11 15:55 UTC, hlapp commented on R/nexml.R
> +#' @param states_as_symbols, logical, default TRUE, when TRUE returns states as symbols otherwise returns states as labels.
I'm thinking more and more that states_as_labels (with a default of FALSE) is the better choice here from an end-user perpective.

2021-08-11 15:55 UTC, hlapp commented on R/nexml.R
> +#' @return data.frame: The character matrix.
We should probably try to say more here about how many leading columns are _not_ actual character state data but IDs etc, and what their column names are going to be. Anyone programming with this will need to know, and so why not document it rather than requiring people to try it out in order to see what comes out.

2021-08-11 18:59 UTC, johnbradley commented on R/nexml.R
> +#' @return data.frame: The character matrix.
I updated the documentation for the return value as follows:
https://github.com/phenoscape/rphenoscape/blob/3483529a1c0910f3e8435e1f3ecd3347e6efd162/R/nexml.R#L439-L442

2021-08-11 19:00 UTC, johnbradley commented on R/nexml.R
> +#' @param states_as_symbols, logical, default TRUE, when TRUE returns states as symbols otherwise returns states as labels.
I switched the code to use states_as_labels.

2021-08-12 12:25 UTC, johnbradley commented
The combined documentation page is from the pre-existing code: http://rphenoscape.phenoscape.org/reference/pk_ontotrace.html. 
I'll separate it out into two pages.

2021-08-12 13:55 UTC, hlapp approved these changes
Almost there 👍🏻 See my inline comments, all of the same kind, and because all would simply involve deleting a line, I'm approving this in advance.

2021-08-12 13:55 UTC, hlapp commented on R/nexml.R
> +#' @rdname get_char_matrix
Do we still need this if there aren't multiple functions in the same Rd? I.e., isn't this determined automatically, and wouldn't we want to use the automatically determined name?

2021-08-12 13:55 UTC, hlapp commented on R/nexml.R
> +#' @name get_char_matrix
Do we still need this if there aren't multiple functions in the same Rd? I.e., isn't this determined automatically, and wouldn't we want to use the automatically determined name?

2021-08-12 13:55 UTC, hlapp commented on R/nexml.R
> +#' @name get_char_matrix_meta
Do we still need this if there aren't multiple functions in the same Rd? I.e., isn't this determined automatically, and wouldn't we want to use the automatically determined name?

2021-08-12 13:55 UTC, hlapp commented on R/nexml.R
> +#' @rdname get_char_matrix_meta
Do we still need this if there aren't multiple functions in the same Rd? I.e., isn't this determined automatically, and wouldn't we want to use the automatically determined name?

2021-08-12 14:27 UTC, merged