Mutual exclusion draft two
phenoscape/rphenoscape pull request #238
Opened 2021-09-20 16:35 UTC by johnbradley

Creating draft pull request to run tests for updated code.

2021-10-05 20:37 UTC, johnbradley commented
I updated the deprecated functions in the mutual-exclusion vignette. 

The source code of the original two functions (`mutual_exclusivity_pair()`  and `mutual_exclusivity()`) was embedded in the mutual-exclusion vignette and goes along with the discussion there.

2021-10-05 22:49 UTC, hlapp commented
@johnbradley did you mean to take this PR out of draft mode?

2021-10-19 20:29 UTC, hlapp commented
Very nice! And that almost half of the time is now spent on API queries is more like how it should be (i.e., that executing necessary API queries is most or at least a large fraction of the execution time).

2022-01-31 20:02 UTC, hlapp requested changes
Sorry for letting this drop off of my radar, @johnbradley. I made some comments and suggestions earlier, but it doesn't seem you've responded to any of those yet? I made a few more.

2022-02-01 18:41 UTC, johnbradley commented on R/mutual_exclusivity.R
> +    is_pair_mutually_exclusive <- exclusivity_types[3]
I agree `exclusivity_types[3]` is rather cryptic.
How about we just use the strings instead of indexing into the array?
Something like this:
```
is_pair_mutually_exclusive <- 'inconclusive_evidence'
```

2022-02-01 18:48 UTC, hlapp commented on R/mutual_exclusivity.R
> +    is_pair_mutually_exclusive <- exclusivity_types[3]
Well, I think what we don't want to do is repeat the strings in multiple places if they're really constants. So declaring them as "constants" (which technically R doesn't have) would be the way to do this. It's unfortunate that R doesn't have an enum type (which I assume continues to be true?).

2022-02-01 19:18 UTC, johnbradley commented on R/mutual_exclusivity.R
> +    num_combinations = ncol(utils::combn(length(phenotypes), 2))
Fixed by [fb6c8a525d99fb62489e17a4504eb25a26ac85d5](https://github.com/phenoscape/rphenoscape/pull/238/commits/fb6c8a525d99fb62489e17a4504eb25a26ac85d5)

2022-02-01 19:21 UTC, johnbradley commented on R/mutual_exclusivity.R
> +mutually_exclusive <- function(phenotypes, studies=NULL, progress_bar=TRUE){
Agreed. Changed in commit https://github.com/phenoscape/rphenoscape/pull/238/commits/9b0a15aa43b16eed0d5a33f7b4e192abf7d56cb1

2022-02-01 19:24 UTC, johnbradley commented
> I made some comments and suggestions earlier, but it doesn't seem you've responded to any of those yet?

@hlapp What comments/suggestions are you referring to? I don't see any earlier comments/suggestions on this PR that haven't already been addressed.

2022-02-01 19:40 UTC, hlapp commented
They're no longer showing as pending now, presumably [you committed them](https://github.com/phenoscape/rphenoscape/pull/238/files/f2f22eb208d6c7321f9a1ae280e763bab8f73166..431dcc0a5ee68f0ffda2e86d805b001a0ae52156).

Looks like the only remaining question is what to do with the vignette. It seems odd (and unhelpful) to repeat definitions of the functions there. I'm torn between retiring the vignette altogether, having the examples section show how to use the function, and having some more extended version of examples in the vignette.

2022-02-01 20:23 UTC, johnbradley commented on R/mutual_exclusivity.R
> +    is_pair_mutually_exclusive <- exclusivity_types[3]
We could create a list:
```
exclusivity_types <- list(strong_compatibility='strong_compatibility',
                          weak_compatibility='weak_compatibility',
                          inconclusive_evidence='inconclusive_evidence',
                          weak_exclusivity='weak_exclusivity',
                          strong_exclusivity='strong_exclusivity')
```
Then use it like so:
```
is_pair_mutually_exclusive <- exclusivity_types$inconclusive_evidence
```
Looks like there are quite a few places where these strings are duplicated.

2022-02-01 20:25 UTC, hlapp commented on R/mutual_exclusivity.R
> +    is_pair_mutually_exclusive <- exclusivity_types[3]
I agree, I guess this comes close.

2022-07-06 19:26 UTC, hlapp approved these changes
I made some improvements to the documentation of the functions. I also decided to delete the vignette for now.

I actually get (clearly unrelated) test failures, using R 3.6.2. I was expecting these to show up in the automated tests too, but the test against 3.6.x seems to be successful, oddly enough.

2022-07-08 14:23 UTC, merged